# Generated by Django 6.0.6 on 2026-06-23 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_number", models.PositiveIntegerField(unique=True)),
                ("occupied", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WaitingVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_no", models.CharField(max_length=20)),
                ("owner_name", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=20)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["queued_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_no", models.CharField(max_length=20, unique=True)),
                ("owner_name", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=20)),
                ("entry_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parking_app.parkingslot",
                    ),
                ),
            ],
        ),
    ]
